### ISSUE TITLE
Validator constructor should warn if not passing in fragment or activity

### ISSUE THREAD

**Issue by tir38** [ragunathjawahar/android-saripaar#151] opened 2016-06-27 17:26 UTC
in Validator class:

```
    public Validator(final Object controller) {
        assertNotNull(controller, "controller");
        mController = controller;
        mValidationMode = Mode.BURST;
        mSequenceComparator = new SequenceComparator();
        mViewValidatedAction = new DefaultViewValidatedAction();

        // Instantiate a ValidationContext
        if (controller instanceof Activity) {
            mValidationContext = new ValidationContext((Activity) controller);
        } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB
                && controller instanceof Fragment) {
            Activity activity = ((Fragment) controller).getActivity();
            mValidationContext = new ValidationContext(activity);
        }
        // Else, lazy init ValidationContext in #getRuleAdapterPair(Annotation, Field)
        // or void #put(VIEW, QuickRule<VIEW>) by obtaining a Context from one of the
        // View instances.
    }
```

If I pass in something other than Fragment or Activity I'll eventually get NPE when trying to access a ValidationContext:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mobsandgeeks.saripaar.ValidationContext.setViewRulesMap(java.util.Map)' on a null object reference
```

I see two options:

1. the simple option is to just warn me with specific RTE

2. make this constructor private and overload with constructors that take in fragment and activities:

```
public Validator(Activity controller) {
    this(controller);
    this.mValidationContext = new ValidationContext((Activity)controller);
}

public Validator(Fragment controller) {
   this(controller);
    if(Build.VERSION.SDK_INT >= 11) {
        Activity activity = ((Fragment)controller).getActivity();
        this.mValidationContext = new ValidationContext(activity);
    } else {
        throw new RuntimeException("...")
    }
}

private Validator(Object controller) {
    assertNotNull(controller, "controller");
    this.mController = controller;
    this.mValidationMode = Validator.Mode.BURST;
    this.mSequenceComparator = new SequenceComparator();
    this.mViewValidatedAction = new DefaultViewValidatedAction();
}
```

**Comment by ragunathjawahar** [comment] 2016-06-29 17:17
@tir38 I notice a missing test case. Could have slipped through it.

**Comment by tir38** [comment] 2016-07-01 02:47
So what do you propose?

**Comment by tir38** [comment] 2016-07-01 02:49
I noticed that this is causing another problem. By not supporting support fragments, the constructor may never create `mValidationContext`, which will NPE when you get to:

````
    private void createRulesSafelyAndLazily(final boolean addingQuickRules) {
        // Create rules lazily, because we don't have to worry about the order of
        // instantiating the Validator.
        if (mViewRulesMap == null) {
            final List<Field> annotatedFields = getSaripaarAnnotatedFields(mController.getClass());
            mViewRulesMap = createRules(annotatedFields);
            mValidationContext.setViewRulesMap(mViewRulesMap);
        }
        ...
```

**Comment by ragunathjawahar** [comment] 2016-07-27 05:24
@tir38 Can't reproduce, checked with native and support `Fragment`s. `mValidationContext` is always initialized.

Please add steps to reproduce. Closing this issue till then.

**Closed by ragunathjawahar** 2016-07-27 05:24 UTC

**Comment by tir38** [comment] 2016-07-28 18:17
Ok I might not be able to reproduce that second part about support fragments, but I think the initial problem still stands. Constructor shouldn't take in `Object` if it can't truly handle any object.

**Comment by ragunathjawahar** [comment] 2016-07-29 05:33
We have the `Object` constructor to allow usage within controllers. If no rules are found (requires at least one `View`, and views have `Context`) an exception is thrown. Check these lines - [Validator.java](https://github.com/ragunathjawahar/android-saripaar/blob/master/saripaar/src/main/java/com/mobsandgeeks/saripaar/Validator.java#L493-L496) for clarification.

**Comment by ragunathjawahar** [comment] 2016-07-29 05:39
Here's a rough [example](https://github.com/ragunathjawahar/android-saripaar/blob/master/saripaar-tests/src/main/java/com/mobsandgeeks/saripaar/tests/ui/QuickRuleOnlyControllerActivity.java#L49-L84).

**Comment by tir38** [comment] 2016-08-01 16:50
Hmm ok. I should have kept track of what I was specifically doing that caused my initial problem. I see the benefit of taking in an Object.

**Comment by ragunathjawahar** [comment] 2016-08-01 17:08
@tir38 Feel free to bring up any concerns that you may have.
