### ISSUE TITLE
Should @Max(value = 50) allow null values

### ISSUE THREAD

**Issue by dotDeeka** [ragunathjawahar/android-saripaar#74] opened 2015-03-19 16:44 UTC
Maybe I'm missing something here...

I have an annotation on an EditText field @Max(value = 50), This fails validation if the EditText is left empty. I feel like this should validate that the field is 50 or less or empty. If I want to also validate that it is not empty I would add the @NotEmpty annotation.

Does that make sense? Or am I completely off base?

**Comment by dotDeeka** [comment] 2015-03-19 16:46
The title was supposed to say "Should" not "Shoule" :)

**Comment by ragunathjawahar** [comment] 2015-03-19 16:51
@dotDeeka `@Max` checks if the field contains an numeric value and if it is less than or equal to the specified value. So, if the field does not contain an numeric value, it is bound to fail. You should use it along with the `@NotEmpty` annotation. Let me know if that helps.

**Comment by dotDeeka** [comment] 2015-03-19 16:54
So the issue I have is I basically only want the field to be validated if it has a value in it. The field is not required. But if it has a value, that value needs to be 50 or less.

**Comment by ragunathjawahar** [comment] 2015-03-19 16:56
@dotDeeka, thank you for clarifying. At the moment, you could use a `QuickRule` to get the job done. There's a pull request regarding the same. I'll close this issue when I fix this problem.

**Comment by dotDeeka** [comment] 2015-03-19 16:58
Awesome @ragunathjawahar , thanks.

**Comment by ragunathjawahar** [comment] 2015-03-19 16:58
@dotDeeka You're welcome :)

**Comment by ragunathjawahar** [comment] 2015-08-01 19:59
@dotDeeka The `2.1.0` version will contain an `@OptionalOrValid` annotation which can be used in combination with rule annotations for `EditText`. If the text is empty, the validation will pass or else we'd validate the field accordingly.

**Comment by dotDeeka** [comment] 2015-08-03 14:40
Thanks @ragunathjawahar, that should achieve the behavior I'm looking for. Thanks.

**Comment by ragunathjawahar** [comment] 2015-08-03 15:09
@dotDeeka You're welcome. Let's just keep this open till I release it.

**Comment by ragunathjawahar** [comment] 2016-06-22 15:31
Duplicate of #102.

**Closed by ragunathjawahar** 2016-06-22 15:31 UTC
