### ISSUE TITLE
Project operation

### ISSUE THREAD

**Issue by wanglg** [ragunathjawahar/android-saripaar#108] opened 2015-08-27 02:23 UTC
showcase not run

**Comment by ragunathjawahar** [comment] 2015-08-27 04:15
The current showcase is based on Kotlin, you need to install the Kotlin plugin. Also, I'll look into it this and come up with a Java version too. Thanks.

**Comment by ragunathjawahar** [comment] 2016-06-22 15:30
Duplicate of #56.

**Closed by ragunathjawahar** 2016-06-22 15:30 UTC
